import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from '@/lib/utils'
import { Outfit, Noto_Sans_Arabic } from 'next/font/google'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        // className={cn(
        //   outfit.variable,
        //   notoSansArabic.variable,
        //   'font-sans antialiased'
        // )}
      >
        {children}
      </body>
    </html>
  );
}
